frr version 9.1
frr defaults datacenter
hostname leaf2
log stdout informational
service integrated-vtysh-config
!
interface lo
 ip address 10.0.0.12/32
!
interface eth1
 description to-spine1
 ipv6 nd ra-interval 5
 no ipv6 nd suppress-ra
!
interface eth2
 description to-spine2
 ipv6 nd ra-interval 5
 no ipv6 nd suppress-ra
!
interface eth3
 description to-gpu-host
 ip address 10.1.2.1/24
!
router bgp 65102
 bgp router-id 10.0.0.12
 bgp bestpath as-path multipath-relax
 neighbor SPINES peer-group
 neighbor SPINES remote-as external
 neighbor SPINES bfd
 neighbor SPINES timers 3 9
 neighbor eth1 interface peer-group SPINES
 neighbor eth2 interface peer-group SPINES
 !
 address-family ipv4 unicast
  network 10.0.0.12/32
  network 10.1.2.0/24
  maximum-paths 16
 exit-address-family
!
line vty
!
